plugins {
    id 'fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
}

def gitCommitHash = { ->
    try {
        ExecOutput result = providers.exec {
            commandLine = ['git', 'rev-parse', '--short', 'HEAD']
            ignoreExitValue = true
        }

        if (result.getResult().get().getExitValue() != 0) {
            return "<UnknownCommit>";
        } else {
            return result.standardOutput.asText.get().strip();
        }
    } catch (Exception e) {
        e.printStackTrace()
        return "<UnknownCommit>";
    }
}
def buildtime = System.currentTimeSeconds()

version = project.mod_version
group = project.maven_group

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

apply plugin: "fabric-loom"

loom {
    runs {
        it.configureEach {
            vmArgs("-Xmx16G")
        }
    }
}

base {
    archivesName = "nvidium"
}

processResources {
    def version = project.version

    inputs.properties("version": version, "commit": gitCommitHash, "buildtime": buildtime)

    filesMatching("fabric.mod.json") {
        expand "commit": gitCommitHash, "version": version, "buildtime": buildtime
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "CaffeineMC"
        url = "https://maven.caffeinemc.net/releases" // or /snapshots
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchmentmc_mappings}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    modImplementation(fabricApi.module("fabric-api-base", project.fabric_version))
    modImplementation(fabricApi.module("fabric-block-view-api-v2", project.fabric_version))
    modImplementation(fabricApi.module("fabric-rendering-fluids-v1", project.fabric_version))
    modImplementation(fabricApi.module("fabric-renderer-api-v1", project.fabric_version))

    modImplementation(fabricApi.module("fabric-resource-loader-v0", project.fabric_version))

    modImplementation "net.caffeinemc:sodium-fabric:0.8.11+mc1.21.11"

    //modImplementation "maven.modrinth:c2me-fabric:0.2.0+alpha.10.49+1.19.4"
    //modImplementation "maven.modrinth:chunks-fade-in:v1.0.3-1.19.4"
    //modImplementation "maven.modrinth:immersiveportals:v2.7.3-mc1.19.4"
    modCompileOnly "maven.modrinth:iris:1.10.4+1.21.11-fabric"
}
