# Nvidium Properties
# Modified by 1Influence for NeoForge port

org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8


mod_version=0.3.0
mod_group_id=me.cortex
mod_id=nvidium


minecraft_version=1.21

neoforge_version=21.0.167



sodium_version=mc1.21.1-0.6.13-neoforge

iris_version=1.8.12+1.21.1-neoforge