# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=26.2
loader_version=0.19.3

# Fabric API
fabric_version=0.153.0+26.2

# Mod Properties
mod_version=0.4.4-beta1-26.2
maven_group=me.cortex
archives_base_name=nvidium
# Dependencies
# check this on https://modmuss50.me/fabric.html
