name: Build nvidium

on:
  pull_request:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Allow execution of gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload nvidium JAR
        uses: actions/upload-artifact@v4
        with:
          name: nvidium
          path: build/libs/nvidium*.jar
          if-no-files-found: error
